name: Auto-Merge Dev to Release

on:
  push:
    branches:
      - dev

jobs:
  merge-to-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge dev into release
        run: |
          git fetch origin
          git checkout release
          git merge origin/dev --no-edit
          git push origin release
